version: '3'

services:
  app:
    image: 'demo:latest'
    build:
      context: ./src/main/docker
    container_name: bookshelf_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/bookshelf
      - spring.datasource.username=postgres
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update
  
  db:
    image: 'postgres:13.1-alpine'
    container_name: bookshelf_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=bookshelf
